/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as PublicarOfertaRouteImport } from './routes/publicar-oferta'
import { Route as PublicarPortfolioRouteImport } from './routes/publicar-portfolio'
import { Route as BarberosBarberIdRouteImport } from './routes/barberos.$barberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarOfertaRoute = PublicarOfertaRouteImport.update({
  id: '/publicar-oferta',
  path: '/publicar-oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarPortfolioRoute = PublicarPortfolioRouteImport.update({
  id: '/publicar-portfolio',
  path: '/publicar-portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberosBarberIdRoute = BarberosBarberIdRouteImport.update({
  id: '/barberos/$barberId',
  path: '/barberos/$barberId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panel': typeof PanelRoute
  '/publicar-oferta': typeof PublicarOfertaRoute
  '/publicar-portfolio': typeof PublicarPortfolioRoute
  '/barberos/$barberId': typeof BarberosBarberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/panel': typeof PanelRoute
  '/publicar-oferta': typeof PublicarOfertaRoute
  '/publicar-portfolio': typeof PublicarPortfolioRoute
  '/barberos/$barberId': typeof BarberosBarberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/panel': typeof PanelRoute
  '/publicar-oferta': typeof PublicarOfertaRoute
  '/publicar-portfolio': typeof PublicarPortfolioRoute
  '/barberos/$barberId': typeof BarberosBarberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/panel'
    | '/publicar-oferta'
    | '/publicar-portfolio'
    | '/barberos/$barberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/panel'
    | '/publicar-oferta'
    | '/publicar-portfolio'
    | '/barberos/$barberId'
  id:
    | '__root__'
    | '/'
    | '/panel'
    | '/publicar-oferta'
    | '/publicar-portfolio'
    | '/barberos/$barberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelRoute: typeof PanelRoute
  PublicarOfertaRoute: typeof PublicarOfertaRoute
  PublicarPortfolioRoute: typeof PublicarPortfolioRoute
  BarberosBarberIdRoute: typeof BarberosBarberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar-oferta': {
      id: '/publicar-oferta'
      path: '/publicar-oferta'
      fullPath: '/publicar-oferta'
      preLoaderRoute: typeof PublicarOfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar-portfolio': {
      id: '/publicar-portfolio'
      path: '/publicar-portfolio'
      fullPath: '/publicar-portfolio'
      preLoaderRoute: typeof PublicarPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barberos/$barberId': {
      id: '/barberos/$barberId'
      path: '/barberos/$barberId'
      fullPath: '/barberos/$barberId'
      preLoaderRoute: typeof BarberosBarberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelRoute: PanelRoute,
  PublicarOfertaRoute: PublicarOfertaRoute,
  PublicarPortfolioRoute: PublicarPortfolioRoute,
  BarberosBarberIdRoute: BarberosBarberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
